"""Safety budgets for one parsed-regulation page returned to clients."""

REGULATION_BLOCKS_PER_PAGE_LIMIT = 250
REGULATION_BLOCK_CONTENT_LIMIT = 100_000
REGULATION_PAGE_CONTENT_LIMIT = 1_000_000
REGULATION_METADATA_ITEM_LIMIT = 2_000
REGULATION_METADATA_ITEMS_PER_FIELD_LIMIT = 20
REGULATION_PAGE_METADATA_LIMIT = 200_000
