import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const commonZh = {
  cancel: '取消', retry: '重试', refresh: '刷新', reload: '重新加载', loading: '页面加载中', delete: '删除', details: '详情', previous: '上一页', next: '下一页',
  page: '页', section: '段', item: '项', findings: '个问题', notProvided: '未填写', notSet: '未设置', currentUser: '当前用户',
  authenticatedUser: '已认证用户', logout: '退出登录', loggedOut: '已退出登录', settings: '设置', expandMenu: '展开菜单',
  collapseMenu: '收起菜单', primaryNavigation: '主导航', shared: '共享知识', private: '私有知识',
}
const commonEn = {
  cancel: 'Cancel', retry: 'Retry', refresh: 'Refresh', reload: 'Reload', loading: 'Loading page', delete: 'Delete', details: 'Details', previous: 'Previous', next: 'Next',
  page: 'page', section: 'section', item: 'items', findings: 'findings', notProvided: 'Not provided', notSet: 'Not set', currentUser: 'Current user',
  authenticatedUser: 'Authenticated user', logout: 'Sign out', loggedOut: 'Signed out', settings: 'Settings', expandMenu: 'Expand menu',
  collapseMenu: 'Collapse menu', primaryNavigation: 'Primary navigation', shared: 'Shared knowledge', private: 'Private knowledge',
}

const resources = {
  zh: { translation: {
    common: commonZh,
    nav: { tasks: '审计任务', documents: '文档中心', regulations: '规则知识库', assistant: 'AI 审计助手', users: '用户管理', reports: '报告中心' },
    header: { search: '搜索任务、文档或法规', light: '切换明亮主题', dark: '切换暗色主题' },
    auth: { title: '登录审计工作台', subtitle: '使用用户名和密码进入系统。', username: '用户名', password: '密码', usernameRequired: '请输入用户名', passwordRequired: '请输入密码', passwordLength: '密码至少 8 个字符', login: '登录', loginSuccess: '登录成功' },
    users: { center: '系统管理', title: '用户管理', subtitle: '管理可登录 AuditMind 的内部账号。', add: '新增用户', createTitle: '创建用户', createDescription: '新用户创建后可立即使用用户名和密码登录。', create: '创建', created: '用户已创建', createFailed: '创建用户失败', deleted: '用户已删除', deleteFailed: '删除用户失败', loadFailed: '用户列表加载失败', total: '共 {{count}} 个用户', username: '用户名', password: '密码', confirmPassword: '确认密码', createdAt: '创建时间', actions: '操作', current: '当前用户', cannotDeleteSelf: '不能删除当前登录用户', confirmDelete: '确认删除用户“{{username}}”？', deleteWarning: '删除后该用户将无法再刷新登录会话。', usernameRequired: '请输入用户名', usernameLength: '用户名需要 3–64 个字符', usernamePattern: '只能使用字母、数字、点、下划线和连字符', passwordRequired: '请输入密码', passwordLength: '密码需要 8–128 个字符', confirmPasswordRequired: '请再次输入密码', passwordMismatch: '两次输入的密码不一致' },
    audit: {
      center: '审计中心', title: '审计任务', subtitle: '支持 PDF 和 Markdown/纯文本，识别风险并定位到原文。', newTask: '新增审计任务', allStatuses: '全部状态', loadFailed: '任务加载失败', empty: '还没有审计任务', paginationTotal: '{{start}}–{{end}} / 共 {{count}} 条', auditDate: '审计日期', taskDetails: '任务详情', retryFailed: '重试失败部分', retryStarted: '已从失败步骤重新开始', retryFailedMessage: '重试失败，请稍后再试', pdfUrlFailed: 'PDF 加载地址获取失败', resultTitle: '第 {{number}} {{unit}}审计结果',
      status: { CREATED: '待开始', RUNNING: '处理中', COMPLETED: '已完成', PARTIAL_FAILED: '部分失败', FAILED: '失败' },
      stage: { UPLOADING: '上传', PARSING: '解析', INDEXING: '索引', AUDITING: '逐页审计', AUDITING_SECTION: '逐段审计', COMPLETED: '完成' },
      create: { breadcrumb: '新增任务', heading: '新增审计任务', subtitle: '上传 PDF 或粘贴 Markdown/纯文本，系统会自动检索有效规则并分段审计。', uploadPdf: '上传 PDF', inputText: '输入 Markdown / 文本', selectPdf: '请选择 PDF 文件', pdfOnly: '仅支持 PDF 文件', dropPdf: '点击或拖拽 PDF 到这里', pdfValidation: '后端仍会校验文件签名和 PDF 结构，不能仅依赖浏览器声明。', contentTitle: '内容标题', contentTitleRequired: '请输入内容标题', titleTooLong: '标题不能超过 252 个字符', titleExample: '例如：第三方平台隐私政策', content: 'Markdown / 纯文本内容', contentRequired: '请输入需要审计的内容', contentExtra: '普通文本也是合法 Markdown；第三方结构化数据请先转换成 Markdown。原文最多 5 MiB。', contentExample: '# 隐私政策\n\n## 信息收集\n\n我们会收集以下信息……', advancedScope: '高级规则范围（默认使用全部可访问的有效规则）', regulations: '指定法规', categories: '知识分类', publicKnowledge: '公共知识', companyRule: '公司规则', submit: '提交并开始审计', submitted: '内容已提交，审计正在后台执行', failed: '创建任务失败' },
      steps: { aria: '审计处理进度', receive: '接收内容', parseText: '解析文本', parsePdf: '解析 PDF', auditPage: '逐页审计', auditSection: '逐段审计', result: '生成结果', failed: '处理失败，可从失败步骤重新开始', partialPage: '审计已结束，部分页面需要重试', partialSection: '审计已结束，部分段落需要重试', completedPage: '所有页面已完成审计', completedSection: '所有段落已完成审计', uploading: '正在保存并校验上传文件', parsingText: '正在解析 Markdown 结构和字符位置', parsingPdf: '正在提取页面文本和定位坐标', preparing: '正在准备逐页审计数据', auditingPage: '正在逐页审计 · 已完成 {{completed}}/{{total}} 页', auditingSection: '正在逐段审计 · 已完成 {{completed}}/{{total}} 段', finalizing: '正在整理审计结果' },
      finding: { waitingPage: '正在等待页面解析完成', waitingSection: '正在等待文本解析完成', failedPage: '该页审计失败', failedSection: '该段审计失败', retryable: '可重试此任务', auditingPage: '正在审计本页内容', auditingSection: '正在审计本段内容', queuedPage: '该页正在排队等待审计', queuedSection: '该段正在排队等待审计', emptyPage: '本页未发现问题', emptySection: '本段未发现问题', recommendation: '整改建议', sourcePage: '第 {{page}} 页', autoRefresh: '完成后审计结果会自动显示，无需刷新页面' },
      viewer: { pdfUnavailable: 'PDF 地址暂不可用', pdfLoadFailed: 'PDF 加载失败，请刷新文件地址', refreshUrl: '刷新文件地址', pageCounter: '第 {{current}} / {{total}} 页', sectionCounter: '第 {{current}} / {{total}} 段', sectionUnavailable: '该段原文暂不可用', image: '[图片：{{name}}]', unnamed: '未命名' },
    },
    regulation: {
      knowledgeCenter: '知识中心', title: '法规知识', detail: '法规详情', subtitle: '统一管理审计依据，让每一项判断都有出处。', add: '新增法规', deleted: '法规知识已删除', back: '返回法规知识', backList: '返回列表', inaccessible: '法规知识不存在或无权查看', searchPlaceholder: '搜索当前页的法规名称、文号或发布机构', allTypes: '全部知识类型', refreshList: '刷新列表', total: '共 {{count}} 条法规',
      sourceType: { LAW: '法律', REGULATION: '行政法规', INDUSTRY_STANDARD: '行业标准', PLATFORM_POLICY: '平台政策', INTERNAL_POLICY: '内部制度', CONTRACT: '合同', CUSTOM_RULE: '自定义规则' },
      status: { UPLOADED: '待解析', PARSING: '解析中', READY: '可用', COMPLETED: '已完成', FAILED: '失败', PENDING: '待处理', PROCESSING: '处理中', DELETING: '删除中，可重试' },
      table: { name: '法规名称', type: '类型', number: '文号', authority: '发布机构', effectiveDate: '生效日期', fileStatus: '文件状态', indexStatus: '索引状态', rules: '规则抽取', updatedAt: '更新时间', actions: '操作', detailPending: '全部处理完成后才可查看详情', deleteProcessing: '法规处理过程中不能删除', confirmDelete: '确认永久删除这条法规知识？', deleteWarning: '原文、解析数据和索引数据将被永久删除，过往审计中的法规证据将无法再追溯核验。此操作不可恢复。', ownerOnly: '只有知识上传者可以删除', loadFailed: '法规列表加载失败', noMatch: '当前页没有匹配的法规', empty: '暂无法规知识', rangeTotal: '{{start}}–{{end}} / 共 {{count}} 条' },
      create: { title: '新增知识', description: '上传 PDF，或直接录入可追溯的 Markdown / 纯文本规则', saveProcess: '保存并开始处理', uploadProcess: '上传并开始处理', uploadPdf: '上传 PDF', inputText: '录入文本', selectPdf: '请选择 PDF 文件', choosePdf: '选择法规 PDF', pdfDescription: 'PDF 会经过 MinerU 解析，并保留页码和原文定位', browse: '浏览文件', sourceText: '知识原文', sourceTextExtra: '支持 Markdown；系统会保留完整原文，规则仍可追溯到这条知识记录。', sourceTextRequired: '请输入知识原文', sourceTextTooLong: '原文不能超过 500000 个字符', textPlaceholder: '# 规则标题\n\n适用主体应当……\n\n## 限制事项\n\n不得……', name: '法规名称', nameRequired: '请输入法规名称', nameExample: '例如：中华人民共和国审计法', number: '文号', numberExample: '例如：主席令第100号', type: '知识类型', visibility: '可见范围', selfOnly: '仅自己可见', authority: '发布机构', authorityExample: '例如：全国人民代表大会', version: '版本', versionExample: '例如：2021 修订版', effectiveDate: '生效日期', expirationDate: '失效日期', selectDate: '选择日期', sourceUrl: '来源链接', validUrl: '请输入有效的 URL', success: '法规知识已新增并开始处理' },
      details: { authority: '发布机构', jurisdiction: '适用地区', effectiveDate: '生效日期', version: '版本', ruleCount: '规则数量', source: '原始来源' },
      rules: { title: '结构化规则', subtitle: '点击规则可定位并高亮 PDF 原文', count: '{{count}} 条', loadFailed: '规则加载失败', loadFailedDescription: '请确认法规规则已经完成抽取。', empty: '该文件尚未生成可用规则', total: '共 {{count}} 条规则', fallback: '规则 {{number}}', unknownPage: '页码未知', singlePage: '第 {{start}} 页', pageRange: '第 {{start}}–{{end}} 页', subject: '责任主体', action: '规范行为', object: '作用对象', condition: '适用条件', timeLimit: '时间限制', requirements: '具体要求', restrictions: '限制事项', exceptions: '例外情形', consequences: '法律后果', type: { REQUIREMENT: '义务要求', PROHIBITION: '禁止行为', RESTRICTION: '限制条件', TIME_LIMIT: '时限要求', PERMISSION: '允许事项', EXCEPTION: '例外情形', RESPONSIBILITY: '责任规定', PENALTY: '处罚后果', APPLICABILITY: '适用范围', RECOMMENDATION: '建议事项' } },
      viewer: { title: '法规原文', refreshUrl: '刷新文件地址', fetchingUrl: '正在获取原文地址', loadFailed: '原文加载失败', expired: '临时地址可能已过期，请刷新后重试。', unavailable: '原文地址暂不可用', readingText: '正在读取知识文本', pdfLoadFailed: 'PDF 加载失败，请刷新文件地址', pageCounter: '第 {{current}} / {{total}} 页', image: '[图片：{{name}}]', unnamed: '未命名' },
    },
    assistant: { workspace: 'AI 工作台', title: '审计助手', deleted: '对话已删除', history: '历史对话', newConversation: '新建对话', emptyHistory: '暂无历史对话', deleteTitle: '删除这个对话？', deleteWarning: '删除后历史消息无法恢复。', rename: '重命名', actions: '对话操作', today: '今天', lastSevenDays: '最近 7 天', earlier: '更早', placeholder: '向 AI 审计助手提问…', knowledgeHint: '法规知识库 · 回答将核验原文依据', stop: '停止生成', send: '发送', disclaimer: 'AI 可能出错，重要审计结论请核对法规原文。', emptyTitle: '今天想审查什么？', emptySubtitle: '基于已验证的法规知识回答问题，并给出可以复核的原文依据。', name: 'AI 审计助手', sourceVerified: '原文来源已核验', sourceVerifiedTip: '来源 Chunk ID 已校验，展示内容由服务端从法规原文补全', sources: '法规依据 · {{count}}', sourcePage: '第 {{page}} 页', generating: '正在生成回答…', unfinished: '上次回答未完成，请重新发送问题。', canceled: '已停止生成', failed: '回答生成失败，请重新发送问题。', copied: '已复制', copy: '复制', enterQuestion: '请输入问题', connectionInterrupted: '对话连接意外中断，请重试', stoppedByUser: '用户已停止生成', connectionError: '对话连接异常，请重试', requestFailed: '对话请求失败（{{status}}）', missingStream: '服务端未返回对话流', phase: { guarding: '正在检查请求安全性', understanding: '正在理解问题意图', retrieving: '正在检索法规知识', reranking: '正在精排相关法规', screeningContext: '正在检查检索内容', generating: '正在生成回答', validating: '正在核验原文依据', screeningOutput: '正在检查回答安全性', agentRunning: '正在分析请求并调用所需工具', validatingResult: '正在核验执行结果', executingApprovedAction: '正在执行已批准的操作' } },
  } },
  en: { translation: {
    common: commonEn,
    nav: { tasks: 'Audit tasks', documents: 'Documents', regulations: 'Rule knowledge base', assistant: 'AI audit assistant', users: 'Users', reports: 'Reports' },
    header: { search: 'Search tasks, documents or policies', light: 'Use light theme', dark: 'Use dark theme' },
    auth: { title: 'Sign in to AuditMind', subtitle: 'Enter your username and password to continue.', username: 'Username', password: 'Password', usernameRequired: 'Enter your username', passwordRequired: 'Enter your password', passwordLength: 'Password must contain at least 8 characters', login: 'Sign in', loginSuccess: 'Signed in' },
    users: { center: 'System management', title: 'Users', subtitle: 'Manage the internal accounts that can sign in to AuditMind.', add: 'Add user', createTitle: 'Create user', createDescription: 'The new user can sign in immediately with this username and password.', create: 'Create', created: 'User created', createFailed: 'Failed to create user', deleted: 'User deleted', deleteFailed: 'Failed to delete user', loadFailed: 'Failed to load users', total: '{{count}} users', username: 'Username', password: 'Password', confirmPassword: 'Confirm password', createdAt: 'Created', actions: 'Actions', current: 'Current user', cannotDeleteSelf: 'You cannot delete the currently signed-in user', confirmDelete: 'Delete user "{{username}}"?', deleteWarning: 'The user will no longer be able to refresh their login session.', usernameRequired: 'Enter a username', usernameLength: 'Username must contain 3–64 characters', usernamePattern: 'Use letters, numbers, dots, underscores, or hyphens only', passwordRequired: 'Enter a password', passwordLength: 'Password must contain 8–128 characters', confirmPasswordRequired: 'Enter the password again', passwordMismatch: 'The passwords do not match' },
    audit: {
      center: 'Audit center', title: 'Audit tasks', subtitle: 'Audit PDF, Markdown, and plain text while locating risks in the source.', newTask: 'New audit task', allStatuses: 'All statuses', loadFailed: 'Failed to load tasks', empty: 'No audit tasks yet', paginationTotal: '{{start}}–{{end}} / {{count}} total', auditDate: 'Audit date', taskDetails: 'Task details', retryFailed: 'Retry failed work', retryStarted: 'Restarted from the failed step', retryFailedMessage: 'Retry failed. Please try again later.', pdfUrlFailed: 'Failed to obtain the PDF URL', resultTitle: '{{unit}} {{number}} audit results',
      status: { CREATED: 'Pending', RUNNING: 'Processing', COMPLETED: 'Completed', PARTIAL_FAILED: 'Partially failed', FAILED: 'Failed' },
      stage: { UPLOADING: 'Upload', PARSING: 'Parse', INDEXING: 'Index', AUDITING: 'Page audit', AUDITING_SECTION: 'Section audit', COMPLETED: 'Complete' },
      create: { breadcrumb: 'New task', heading: 'New audit task', subtitle: 'Upload a PDF or paste Markdown/plain text. The system retrieves effective rules and audits each section.', uploadPdf: 'Upload PDF', inputText: 'Enter Markdown / text', selectPdf: 'Select a PDF file', pdfOnly: 'Only PDF files are supported', dropPdf: 'Click or drag a PDF here', pdfValidation: 'The server validates the file signature and PDF structure instead of trusting the browser declaration.', contentTitle: 'Content title', contentTitleRequired: 'Enter a content title', titleTooLong: 'The title cannot exceed 252 characters', titleExample: 'Example: Third-party platform privacy policy', content: 'Markdown / plain text', contentRequired: 'Enter the content to audit', contentExtra: 'Plain text is valid Markdown. Convert third-party structured data to Markdown first. Maximum source size: 5 MiB.', contentExample: '# Privacy Policy\n\n## Information Collection\n\nWe collect the following information…', advancedScope: 'Advanced rule scope (all accessible effective rules are used by default)', regulations: 'Specified regulations', categories: 'Knowledge categories', publicKnowledge: 'Public knowledge', companyRule: 'Company rules', submit: 'Submit and start audit', submitted: 'Content submitted. The audit is running in the background.', failed: 'Failed to create task' },
      steps: { aria: 'Audit progress', receive: 'Receive content', parseText: 'Parse text', parsePdf: 'Parse PDF', auditPage: 'Audit pages', auditSection: 'Audit sections', result: 'Generate results', failed: 'Processing failed. You can restart from the failed step.', partialPage: 'Audit finished; some pages need to be retried.', partialSection: 'Audit finished; some sections need to be retried.', completedPage: 'All pages have been audited.', completedSection: 'All sections have been audited.', uploading: 'Saving and validating the uploaded file', parsingText: 'Parsing Markdown structure and character positions', parsingPdf: 'Extracting page text and coordinates', preparing: 'Preparing page audit data', auditingPage: 'Auditing pages · {{completed}}/{{total}} completed', auditingSection: 'Auditing sections · {{completed}}/{{total}} completed', finalizing: 'Finalizing audit results' },
      finding: { waitingPage: 'Waiting for the page to finish parsing', waitingSection: 'Waiting for the text to finish parsing', failedPage: 'This page audit failed', failedSection: 'This section audit failed', retryable: 'You can retry this task', auditingPage: 'Auditing this page', auditingSection: 'Auditing this section', queuedPage: 'This page is queued for audit', queuedSection: 'This section is queued for audit', emptyPage: 'No findings on this page', emptySection: 'No findings in this section', recommendation: 'Remediation', sourcePage: 'Page {{page}}', autoRefresh: 'Results appear automatically when complete; no refresh is needed.' },
      viewer: { pdfUnavailable: 'PDF URL is temporarily unavailable', pdfLoadFailed: 'Failed to load the PDF. Refresh the file URL.', refreshUrl: 'Refresh file URL', pageCounter: 'Page {{current}} / {{total}}', sectionCounter: 'Section {{current}} / {{total}}', sectionUnavailable: 'Source text is unavailable for this section', image: '[Image: {{name}}]', unnamed: 'Unnamed' },
    },
    regulation: {
      knowledgeCenter: 'Knowledge center', title: 'Regulations', detail: 'Regulation details', subtitle: 'Manage audit authority in one place and keep every finding traceable.', add: 'Add regulation', deleted: 'Regulation deleted', back: 'Back to regulations', backList: 'Back to list', inaccessible: 'This regulation does not exist or you do not have access.', searchPlaceholder: 'Search this page by title, document number, or authority', allTypes: 'All knowledge types', refreshList: 'Refresh list', total: '{{count}} regulations',
      sourceType: { LAW: 'Law', REGULATION: 'Administrative regulation', INDUSTRY_STANDARD: 'Industry standard', PLATFORM_POLICY: 'Platform policy', INTERNAL_POLICY: 'Internal policy', CONTRACT: 'Contract', CUSTOM_RULE: 'Custom rule' },
      status: { UPLOADED: 'Pending parse', PARSING: 'Parsing', READY: 'Available', COMPLETED: 'Completed', FAILED: 'Failed', PENDING: 'Pending', PROCESSING: 'Processing', DELETING: 'Deleting; retry available' },
      table: { name: 'Regulation', type: 'Type', number: 'Document no.', authority: 'Authority', effectiveDate: 'Effective date', fileStatus: 'File status', indexStatus: 'Index status', rules: 'Rule extraction', updatedAt: 'Updated', actions: 'Actions', detailPending: 'Details are available after all processing completes', deleteProcessing: 'A regulation cannot be deleted while it is processing', confirmDelete: 'Permanently delete this regulation?', deleteWarning: 'The source, parsed data, and index data will be permanently deleted. Evidence in previous audits can no longer be traced or verified. This cannot be undone.', ownerOnly: 'Only the uploader can delete this knowledge item', loadFailed: 'Failed to load regulations', noMatch: 'No regulations on this page match the search', empty: 'No regulations available', rangeTotal: '{{start}}–{{end}} / {{count}} total' },
      create: { title: 'Add knowledge', description: 'Upload a PDF or enter traceable Markdown / plain-text rules', saveProcess: 'Save and process', uploadProcess: 'Upload and process', uploadPdf: 'Upload PDF', inputText: 'Enter text', selectPdf: 'Select a PDF file', choosePdf: 'Choose regulation PDF', pdfDescription: 'MinerU parses the PDF while preserving page numbers and source positions', browse: 'Browse', sourceText: 'Source text', sourceTextExtra: 'Markdown is supported. The complete source is preserved so extracted rules remain traceable.', sourceTextRequired: 'Enter source text', sourceTextTooLong: 'Source text cannot exceed 500,000 characters', textPlaceholder: '# Rule title\n\nThe applicable entity shall…\n\n## Restrictions\n\nMust not…', name: 'Regulation name', nameRequired: 'Enter a regulation name', nameExample: 'Example: Audit Act', number: 'Document number', numberExample: 'Example: Order No. 100', type: 'Knowledge type', visibility: 'Visibility', selfOnly: 'Only me', authority: 'Authority', authorityExample: 'Example: National legislature', version: 'Version', versionExample: 'Example: 2021 revision', effectiveDate: 'Effective date', expirationDate: 'Expiration date', selectDate: 'Select date', sourceUrl: 'Source URL', validUrl: 'Enter a valid URL', success: 'Knowledge added and processing started' },
      details: { authority: 'Authority', jurisdiction: 'Jurisdiction', effectiveDate: 'Effective date', version: 'Version', ruleCount: 'Rules', source: 'Original source' },
      rules: { title: 'Structured rules', subtitle: 'Select a rule to locate and highlight its PDF source', count: '{{count}} rules', loadFailed: 'Failed to load rules', loadFailedDescription: 'Confirm that rule extraction has completed.', empty: 'No usable rules have been generated for this file', total: '{{count}} rules total', fallback: 'Rule {{number}}', unknownPage: 'Page unknown', singlePage: 'Page {{start}}', pageRange: 'Pages {{start}}–{{end}}', subject: 'Responsible party', action: 'Required action', object: 'Object', condition: 'Conditions', timeLimit: 'Time limit', requirements: 'Requirements', restrictions: 'Restrictions', exceptions: 'Exceptions', consequences: 'Consequences', type: { REQUIREMENT: 'Requirement', PROHIBITION: 'Prohibition', RESTRICTION: 'Restriction', TIME_LIMIT: 'Time limit', PERMISSION: 'Permission', EXCEPTION: 'Exception', RESPONSIBILITY: 'Responsibility', PENALTY: 'Penalty', APPLICABILITY: 'Applicability', RECOMMENDATION: 'Recommendation' } },
      viewer: { title: 'Regulation source', refreshUrl: 'Refresh file URL', fetchingUrl: 'Obtaining source URL', loadFailed: 'Failed to load source', expired: 'The temporary URL may have expired. Refresh and try again.', unavailable: 'Source URL is temporarily unavailable', readingText: 'Reading knowledge text', pdfLoadFailed: 'Failed to load the PDF. Refresh the file URL.', pageCounter: 'Page {{current}} / {{total}}', image: '[Image: {{name}}]', unnamed: 'Unnamed' },
    },
    assistant: { workspace: 'AI workspace', title: 'Audit assistant', deleted: 'Conversation deleted', history: 'Conversation history', newConversation: 'New conversation', emptyHistory: 'No conversation history', deleteTitle: 'Delete this conversation?', deleteWarning: 'Deleted messages cannot be recovered.', rename: 'Rename', actions: 'Conversation actions', today: 'Today', lastSevenDays: 'Last 7 days', earlier: 'Earlier', placeholder: 'Ask the AI audit assistant…', knowledgeHint: 'Regulation knowledge base · Answers are verified against source text', stop: 'Stop generating', send: 'Send', disclaimer: 'AI can make mistakes. Verify important audit conclusions against the original regulation.', emptyTitle: 'What would you like to audit today?', emptySubtitle: 'Ask questions using verified regulation knowledge and reviewable source evidence.', name: 'AI audit assistant', sourceVerified: 'Source verified', sourceVerifiedTip: 'Source chunk IDs were validated and display text was filled from the original regulation', sources: 'Regulation sources · {{count}}', sourcePage: 'Page {{page}}', generating: 'Generating an answer…', unfinished: 'The previous answer was not completed. Please send the question again.', canceled: 'Generation stopped', failed: 'Answer generation failed. Please send the question again.', copied: 'Copied', copy: 'Copy', enterQuestion: 'Enter a question', connectionInterrupted: 'The conversation connection ended unexpectedly. Please retry.', stoppedByUser: 'Generation stopped by the user', connectionError: 'Conversation connection failed. Please retry.', requestFailed: 'Conversation request failed ({{status}})', missingStream: 'The server did not return a conversation stream', phase: { guarding: 'Checking request safety', understanding: 'Understanding your intent', retrieving: 'Searching regulation knowledge', reranking: 'Reranking relevant regulations', screeningContext: 'Screening retrieved context', generating: 'Generating the answer', validating: 'Validating source evidence', screeningOutput: 'Screening answer safety', agentRunning: 'Analyzing the request and calling the required tools', validatingResult: 'Validating the execution result', executingApprovedAction: 'Executing the approved action' } },
  } },
} as const

const savedLanguage = typeof localStorage === 'undefined' ? undefined : localStorage.getItem('auditmind-language')

void i18n.use(initReactI18next).init({ resources, lng: savedLanguage ?? 'zh', fallbackLng: 'zh', interpolation: { escapeValue: false } })

export default i18n
